#!/bin/bash
# install_agent.sh — Install WallyWatcher launchd agent (portable).
#
# Resolves all paths at install time (current repo location, $HOME, python).
# Run from anywhere: `bash .claude/watcher/install_agent.sh`
#
# What it does:
#   1. Detects REPO_ROOT (2 levels up from this script)
#   2. Detects PYTHON (prefers python3.13, falls back to python3)
#   3. Copies WallyWatcher.app from repo → ~/.local/Applications/
#   4. Writes ~/.config/wallytrader.conf with REPO_ROOT + PYTHON
#   5. Renders launchd plist from template → ~/Library/LaunchAgents/
#   6. Registers app with LaunchServices (for icon in Background Items)
#   7. Loads launchd agent
#
# Idempotent — safe to re-run after git pull or path changes.

set -eu

# 1. Resolve paths at runtime
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# 2. Detect Python (prefers newer, falls back)
PYTHON=""
for candidate in \
    "/opt/homebrew/bin/python3.13" \
    "/opt/homebrew/bin/python3.12" \
    "/opt/homebrew/bin/python3" \
    "/usr/local/bin/python3.13" \
    "/usr/local/bin/python3.12" \
    "/usr/local/bin/python3"; do
    if [ -x "$candidate" ]; then
        PYTHON="$candidate"
        break
    fi
done

if [ -z "$PYTHON" ]; then
    echo "ERROR: No suitable Python 3 found." >&2
    echo "Install via: brew install python@3.13" >&2
    exit 1
fi

# 3. Verify Python deps
if ! "$PYTHON" -c "import requests, yaml, dateutil" 2>/dev/null; then
    echo "Installing Python deps (requests, pyyaml, python-dateutil, pytest)..."
    "$PYTHON" -m pip install --break-system-packages --quiet \
        requests python-dateutil pyyaml pytest
fi

# 4. Copy bundle to user-local Applications
APP_SRC="$SCRIPT_DIR/WallyWatcher.app"
APP_DEST="$HOME/.local/Applications/WallyWatcher.app"

if [ ! -d "$APP_SRC" ]; then
    echo "ERROR: Source bundle not found: $APP_SRC" >&2
    exit 1
fi

mkdir -p "$(dirname "$APP_DEST")"
if [ -d "$APP_DEST" ]; then
    rm -rf "$APP_DEST"
fi
cp -R "$APP_SRC" "$APP_DEST"
chmod +x "$APP_DEST/Contents/MacOS/WallyWatcher"

# 5. Write runtime config
CONFIG_DIR="$HOME/.config"
CONFIG_FILE="$CONFIG_DIR/wallytrader.conf"
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# Wally Trader watcher runtime config.
# Generated by $SCRIPT_DIR/install_agent.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Safe to edit manually — re-running install_agent.sh overwrites.

REPO_ROOT="$REPO_ROOT"
PYTHON="$PYTHON"
EOF

# 6. Render launchd plist
PLIST_SRC="$SCRIPT_DIR/launchd/com.wallytrader.watcher.plist.template"
PLIST_DEST="$HOME/Library/LaunchAgents/com.wallytrader.watcher.plist"
APP_EXECUTABLE="$APP_DEST/Contents/MacOS/WallyWatcher"

mkdir -p "$(dirname "$PLIST_DEST")"
sed "s|__APP_EXECUTABLE__|$APP_EXECUTABLE|g" "$PLIST_SRC" > "$PLIST_DEST"

# 7. Register bundle with LaunchServices (so icon shows in Background Items)
LSREG="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
if [ -x "$LSREG" ]; then
    "$LSREG" -f "$APP_DEST" >/dev/null 2>&1 || true
fi

# 8. Unload if already loaded, then load
launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl load "$PLIST_DEST"

echo ""
echo "WallyWatcher installed."
echo "  Bundle:  $APP_DEST"
echo "  Plist:   $PLIST_DEST"
echo "  Config:  $CONFIG_FILE"
echo "  Repo:    $REPO_ROOT"
echo "  Python:  $PYTHON"
echo ""
echo "Test immediately:  launchctl start com.wallytrader.watcher"
echo "Tail logs:         tail -f /tmp/wally_watcher.out"
echo "Dashboard:         cat $REPO_ROOT/.claude/watcher/dashboard.md"
echo ""
echo "Background Items shows: \"Wally Trader Watcher\" with dachshund icon."
echo "If still showing \"bash\", cierra/reabre System Settings."
echo ""
echo "Uninstall:  bash $SCRIPT_DIR/uninstall_agent.sh"
